.Dd August 5, 2021
.Dt TRANSLIT 1
.Os
.Sh NAME
.Nm cyr2lat
.Nd transliterates input from Serbian Cyrillic to Latin
.Sh USAGE
.Nm cyr2lat \(lB file ... \(rB
.Sh FUNCTION
.Nm
reads lines of UTF-8 Serbian Cyrillic text from input and writes corresponding lines of Serbian Latin text to standard output.

cyr2lat requires AWK with UTF-8 support. It will search the PATH for `gawk'.
.Sh AUTHOR
.Nm Written by Vladimir Vrzić
.Sh LICENSE
.Nm
is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.
