#!/bin/sh
# transliterate input from UTF-8 Serbian Latin to 7-bit ASCII
# Usage: lat2ascii [ file ... ]
# Requires: AWK that supports UTF-8 (looks for GNU AWK)
# Author: Vladimir Vrzić
#
# lat2ascii is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.

searchpath() {
# Usage: searchpath progname path
  IFS=${PATH_SEPARATOR-":"} prog=':'
  for dir in $2; do
    # try `progname' with all well known extensions
    for ext in '' '.exe'; do
      try="$dir/$1$ext"
      test -f "$try" && test -x "$try" && prog="$try" && break
    done
    test "$prog" = ":" || break
  done
  echo "$prog"
}

AWK=$(searchpath gawk "$PATH")
if [ "$AWK" = ":" ]; then
  echo >&2 "$0: Cannot find gawk in PATH"
  exit 1
fi

awkscript='
BEGIN {
  m["Č"] = "C" ; m["č"] = "c"
  m["Ć"] = "C" ; m["ć"] = "c"
  m["Đ"] = "Dj"; m["đ"] = "dj"
  m["Š"] = "S" ; m["š"] = "s"
  m["Ž"] = "Z" ; m["ž"] = "z"
  FS=""
}
{
  for (i = 1; i <= NF; j = ++i + 1) {
    if (i < NF && ($i == "D" || $i == "d") && $j == "ž") {
        printf("%sz", $i)
        ++i
        continue;
    }
    if (m[$i]) {
      printf("%s", m[$i])
    } else {
      printf("%s", $i)
    }
  }
  printf("\n")
}
'

exec $AWK "$awkscript" "$@"
